export { HomePage } from './HomePage';
export { LoginPage } from './LoginPage';
export { CadastroPage } from './CadastroPage';
export { DashboardPage } from './DashboardPage';
export { ServicesPage } from './ServicesPage';
export { ProfilePage } from './ProfilePage';
export { HeatmapPage } from './HeatmapPage';
export { HeatmapViewPage } from './HeatmapViewPage';
export { EngajamentoPage } from './EngajamentoPage';
